# Generated by Django 4.2.4 on 2023-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='companyname',
            field=models.CharField(default='firma', max_length=50),
        ),
    ]
