# Generated by Django 4.2.4 on 2023-09-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitsinstock',
            field=models.IntegerField(default='laku'),
        ),
    ]
