# Generated by Django 4.2.4 on 2023-09-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_unitsinstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='firma', max_length=50)),
                ('carname', models.CharField(default='firma', max_length=50)),
                ('carmodel', models.CharField(default='firma', max_length=50)),
                ('drivenkm', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
            ],
        ),
    ]
