# Generated by Django 4.2.4 on 2023-09-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='firma', max_length=50)),
                ('shoptown', models.CharField(default='firma', max_length=50)),
                ('shopaddress', models.CharField(default='firma', max_length=50)),
            ],
        ),
    ]
